apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: student-api-demo
  name: student-api-demo
  namespace: student-namespace-v1
spec:
  replicas: 2
  selector:
    name: student-api-demo
  template:
    metadata:
      labels:
        name: student-api-demo
    spec:
      containers:
      - image: abhishekbadwaik/golang-student-api-k8s-v1
        name: student-api-demo
        ports:
        - containerPort: 9000


